Implemented a very basic ground-console-UI that saves data into the MySQL-database, the .txt-file in the program however to mongoDB it threws an exception
org.springframework.dao.InvalidDataAccessApiUsageException: Cannot autogenerate id of type java.lang.Long for entity of type KafkaGroup.BumbiBearApp.payload.User

Because of the Long value that mySQL needs, but mongoDB really doesnt like.. MySQL wants to autogenerate Id:s with help of this value but mongoDB likes to generate their own, hence why they dont like the extra "id"- field.